name: Publish package to Maven Central

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java 环境 (例如 JDK 17)
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 3. 导入 GPG 私钥
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # 4. 执行发布命令
      #    -B 表示批处理模式，避免交互
      #    -s .github/settings.xml 指定 Maven 配置文件
      #    -DskipTests 跳过测试，加快发布速度（可选）
      #    -Dgpg.passphrase 将 GPG 密码传递给插件
      #    MAVEN_USERNAME 和 MAVEN_PASSWORD 是为 settings.xml 准备的环境变量
      - name: Publish to Central Repository
        run: >
          mvn -B deploy -s .github/settings.xml -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}